import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from 'huntingcoder/styles/Home.module.css'
import Link from 'next/link'
// import script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="nextjs, huntingcoder blog" />
        {/* use above to declare keywords for SEO */}
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"></link>
      </Head>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous" strategy="lazyOnload"></script>
      {/* script can be used as above and can used for lazyload (import script from 'next/script' is used for this purpose) */}
      <nav className="navbar navbar-expand-lg bg-body-tertiary">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">Navbar</a>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav me-auto mb-2 mb-lg-0">
              <Link href='/'><li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li></Link>
              <Link href='/about'><li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">About</a>
              </li></Link>
              <Link href='/blog'><li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Blogs</a>
              </li></Link>
              <Link href='/contact'><li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Contact us</a>
              </li></Link>
            </ul>
          </div>
        </div>
      </nav>
    </>
  )
}
















